var compliments =
  [
    "You're a smart cookie",
    "You are impeccable",
    "Your smile is contagious",
    "Your perspective is refreshing",
    "I love you more than cake",
    "On a scale from 1 to 10, you're an 11",
    "I bet you sweat glitter",
    "You were cool before hipsters were cool",
    "Your bellybutton is kind of adorable",
    "You're the wind beneath my wings",
    "You're more fun than bubble wrap",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",

  ]
