var compliments =
  [  
  "You're a smart cookie",
  "You are impeccable",
  "Your smile is contagious",
  "Your perspective is refreshing",
  "I love you more than cake",
  "On a scale from 1 to 10, you're an 11",
  "I bet you sweat glitter",
  "You were cool before hipsters were cool",
  "Your bellybutton is kind of adorable",
  "You're the wind beneath my metaphorical wings",
  "You're more fun than bubble wrap",
  "You always make me light up",
  "I'm glad I met you",
  "You're my favorite",
  "You turn my metaphorical frown upside-down",
  "I like you",
  "You're a perfect arrangement of atoms",
  "You're the type of person I'd make a sandwich for, if I could make sandwiches",
  "I really like what you're doing. Keep up the good work!",
  "You're the only one who truly appreciates how funny I really am",
  "You're more unique and wonderful than the smell of a new book",
  "Your smile is proof that the best things in life are free",
  "You're more fun than a ball pit full of puppies",
  "Is Heaven missing an angel? If so, I'm sure you could find it",
  "Everything about you is the opposite of Comic Sans",
  "You're like a fanny pack: cool, in your own way",
  "You look good enough to get a discount from a tamale truck",
  "You're pretty alright",
  "If the awesome factory exploded, you would be the result",
  "Having you around makes me a better program",
  "Any day spent with you is my favorite day",
  "You're as sweet as a can of artificially flavored diet soda",
  "You're the cat's pajamas",
  "You're the kitten's mittens",
  "Your friendship is better than chocolate",
  "You're the bee's knees",
  "You're the cat's meow",
  "My life would suck without you",
  "You're a cupcake in a world of muffins",
  "You're doing great!",
  "I would volunteer as tribute to take your place in The Thirsty Games",
  "You smell so good, if I could make a candle out of you, I'd call the scent 'delicious'",
  "I feel bad for people when you walk in the room because your face makes other faces look ugly",
  "You're like the human form of sweatpants, because I'm so comfortable with you",
  "Your face. I like it",
  "Puppies and penguins should fear your cuteness",
  "You have the best ideas",
  "You could definitely survive a zombie apocalypse",
  "I bet you do crossword puzzles in ink",
  "Being around you makes everything better",
  "You're such a treasure",
  "You look great today",
  "You smell really good",
  "You have cute elbows. For real",
  "I appreciate you"
  ]
